namespace ProyectoIS
{
    partial class LogIn
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.subtituloLogin = new System.Windows.Forms.Label();
            this.txtUser = new System.Windows.Forms.TextBox();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.tarjetaLogin = new ProyectoIS.UsuariosRoundedPanel();
            this.campoUsuario = new ProyectoIS.UsuariosRoundedPanel();
            this.campoClave = new ProyectoIS.UsuariosRoundedPanel();
            this.insigniaLogin = new ProyectoIS.UsuariosRoundedPanel();
            this.iconoLogin = new ProyectoIS.LoginGlyph();
            this.iconoUsuarioLogin = new ProyectoIS.LoginGlyph();
            this.iconoClaveLogin = new ProyectoIS.LoginGlyph();
            this.btnLogIn = new ProyectoIS.UsuariosRoundedButton();
            this.btnCambiar = new ProyectoIS.UsuariosRoundedButton();
            this.temaLogin = new ProyectoIS.UsuariosThemeSwitch();
            this.mostrarClave = new ProyectoIS.LoginEyeButton();
            this.SuspendLayout();
            this.label1.Name = "label1";
            this.label2.Name = "label2";
            this.label3.Name = "label3";
            this.subtituloLogin.Name = "subtituloLogin";
            this.txtUser.Name = "txtUser";
            this.txtPassword.Name = "txtPassword";
            this.tarjetaLogin.Name = "tarjetaLogin";
            this.campoUsuario.Name = "campoUsuario";
            this.campoClave.Name = "campoClave";
            this.insigniaLogin.Name = "insigniaLogin";
            this.iconoLogin.Name = "iconoLogin";
            this.iconoUsuarioLogin.Name = "iconoUsuarioLogin";
            this.iconoClaveLogin.Name = "iconoClaveLogin";
            this.btnLogIn.Name = "btnLogIn";
            this.btnCambiar.Name = "btnCambiar";
            this.temaLogin.Name = "temaLogin";
            this.mostrarClave.Name = "mostrarClave";
            this.temaLogin.Location = new System.Drawing.Point(410, 20);
            this.temaLogin.Size = new System.Drawing.Size(94, 38);
            this.temaLogin.TabIndex = 1;
            this.temaLogin.Click += new System.EventHandler(this.temaLogin_Click);
            this.insigniaLogin.Location = new System.Drawing.Point(227, 65);
            this.insigniaLogin.Size = new System.Drawing.Size(86, 86);
            this.insigniaLogin.CornerRadius = 18;
            this.insigniaLogin.BackColor = System.Drawing.Color.FromArgb(45, 96, 196);
            this.insigniaLogin.BorderColor = System.Drawing.Color.FromArgb(45, 96, 196);
            this.iconoLogin.Location = new System.Drawing.Point(24, 20);
            this.iconoLogin.Size = new System.Drawing.Size(38, 44);
            this.iconoLogin.Lock = true;
            this.iconoLogin.ForeColor = System.Drawing.Color.White;
            this.iconoLogin.BackColor = System.Drawing.Color.Transparent;
            this.insigniaLogin.Controls.Add(this.iconoLogin);
            this.label3.Location = new System.Drawing.Point(24, 172);
            this.label3.Size = new System.Drawing.Size(492, 46);
            this.label3.Font = new System.Drawing.Font("Segoe UI", 25F, System.Drawing.FontStyle.Bold);
            this.label3.Text = "¡Bienvenido!";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.subtituloLogin.Location = new System.Drawing.Point(24, 222);
            this.subtituloLogin.Size = new System.Drawing.Size(492, 30);
            this.subtituloLogin.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.subtituloLogin.Text = "Ingresá tus datos para continuar";
            this.subtituloLogin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.subtituloLogin.ForeColor = System.Drawing.Color.FromArgb(103, 110, 124);
            this.tarjetaLogin.Location = new System.Drawing.Point(34, 275);
            this.tarjetaLogin.Size = new System.Drawing.Size(472, 337);
            this.tarjetaLogin.CornerRadius = 18;
            this.tarjetaLogin.TabIndex = 0;
            this.tarjetaLogin.BackColor = System.Drawing.Color.White;
            this.tarjetaLogin.BorderColor = System.Drawing.Color.FromArgb(208, 214, 225);
            this.label1.Location = new System.Drawing.Point(24, 23);
            this.label1.Size = new System.Drawing.Size(400, 24);
            this.label1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.label1.Text = "Usuario";
            this.tarjetaLogin.Controls.Add(this.label1);
            this.campoUsuario.Location = new System.Drawing.Point(24, 50);
            this.campoUsuario.Size = new System.Drawing.Size(424, 46);
            this.campoUsuario.CornerRadius = 11;
            this.campoUsuario.TabIndex = 0;
            this.campoUsuario.BackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.campoUsuario.BorderColor = System.Drawing.Color.FromArgb(208, 214, 225);
            this.campoUsuario.ForeColor = System.Drawing.Color.FromArgb(102, 112, 130);
            this.iconoUsuarioLogin.Location = new System.Drawing.Point(14, 12);
            this.iconoUsuarioLogin.Size = new System.Drawing.Size(22, 22);
            this.iconoUsuarioLogin.Lock = false;
            this.iconoUsuarioLogin.BackColor = System.Drawing.Color.Transparent;
            this.campoUsuario.Controls.Add(this.iconoUsuarioLogin);
            this.txtUser.Location = new System.Drawing.Point(46, 13);
            this.txtUser.Size = new System.Drawing.Size(360, 24);
            this.txtUser.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.txtUser.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtUser.TabIndex = 0;
            this.txtUser.BackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.txtUser.ForeColor = System.Drawing.Color.FromArgb(35, 39, 45);
            this.txtUser.Enter += new System.EventHandler(this.campoLogin_Enter);
            this.txtUser.Leave += new System.EventHandler(this.campoLogin_Leave);
            this.campoUsuario.Controls.Add(this.txtUser);
            this.tarjetaLogin.Controls.Add(this.campoUsuario);
            this.label2.Location = new System.Drawing.Point(24, 107);
            this.label2.Size = new System.Drawing.Size(400, 24);
            this.label2.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.label2.Text = "Contraseña";
            this.tarjetaLogin.Controls.Add(this.label2);
            this.campoClave.Location = new System.Drawing.Point(24, 134);
            this.campoClave.Size = new System.Drawing.Size(424, 46);
            this.campoClave.CornerRadius = 11;
            this.campoClave.TabIndex = 1;
            this.campoClave.BackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.campoClave.BorderColor = System.Drawing.Color.FromArgb(208, 214, 225);
            this.campoClave.ForeColor = System.Drawing.Color.FromArgb(102, 112, 130);
            this.iconoClaveLogin.Location = new System.Drawing.Point(14, 12);
            this.iconoClaveLogin.Size = new System.Drawing.Size(22, 22);
            this.iconoClaveLogin.Lock = true;
            this.iconoClaveLogin.BackColor = System.Drawing.Color.Transparent;
            this.campoClave.Controls.Add(this.iconoClaveLogin);
            this.txtPassword.Location = new System.Drawing.Point(46, 13);
            this.txtPassword.Size = new System.Drawing.Size(328, 24);
            this.txtPassword.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.txtPassword.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtPassword.TabIndex = 0;
            this.txtPassword.BackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.txtPassword.ForeColor = System.Drawing.Color.FromArgb(35, 39, 45);
            this.txtPassword.Enter += new System.EventHandler(this.campoLogin_Enter);
            this.txtPassword.Leave += new System.EventHandler(this.campoLogin_Leave);
            this.campoClave.Controls.Add(this.txtPassword);
            this.tarjetaLogin.Controls.Add(this.campoClave);
            this.txtPassword.UseSystemPasswordChar = true;
            this.txtUser.HandleCreated += new System.EventHandler(this.txtUser_HandleCreated);
            this.mostrarClave.Location = new System.Drawing.Point(380, 8);
            this.mostrarClave.Size = new System.Drawing.Size(30, 28);
            this.mostrarClave.TabIndex = 1;
            this.mostrarClave.BackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.mostrarClave.HoverBackColor = System.Drawing.Color.FromArgb(249, 250, 252);
            this.mostrarClave.ForeColor = System.Drawing.Color.FromArgb(102, 112, 130);
            this.mostrarClave.FlatAppearance.BorderSize = 0;
            this.mostrarClave.Click += new System.EventHandler(this.mostrarClave_Click);
            this.campoClave.Controls.Add(this.mostrarClave);
            this.btnLogIn.Location = new System.Drawing.Point(24, 204);
            this.btnLogIn.Size = new System.Drawing.Size(424, 46);
            this.btnLogIn.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.btnLogIn.TabIndex = 2;
            this.btnLogIn.Text = "Ingresar";
            this.btnLogIn.Icon = ProyectoIS.UsuariosButtonIcon.Arrow;
            this.btnLogIn.Click += new System.EventHandler(this.btnLogIn_Click);
            this.tarjetaLogin.Controls.Add(this.btnLogIn);
            this.btnCambiar.Location = new System.Drawing.Point(24, 266);
            this.btnCambiar.Size = new System.Drawing.Size(424, 46);
            this.btnCambiar.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.btnCambiar.TabIndex = 3;
            this.btnCambiar.Text = "Cambiar contraseña";
            this.btnCambiar.Icon = ProyectoIS.UsuariosButtonIcon.Key;
            this.btnCambiar.Click += new System.EventHandler(this.btnCambiar_Click);
            this.tarjetaLogin.Controls.Add(this.btnCambiar);
            this.btnLogIn.BackColor = System.Drawing.Color.FromArgb(45, 96, 196);
            this.btnLogIn.ForeColor = System.Drawing.Color.White;
            this.btnLogIn.FlatAppearance.BorderSize = 0;
            this.btnCambiar.Tag = "secondary";
            this.btnCambiar.BackColor = System.Drawing.Color.White;
            this.btnCambiar.ForeColor = System.Drawing.Color.FromArgb(45, 96, 196);
            this.btnCambiar.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(45, 96, 196);
            this.btnCambiar.FlatAppearance.BorderSize = 1;
            this.Controls.Add(this.temaLogin);
            this.Controls.Add(this.insigniaLogin);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.subtituloLogin);
            this.Controls.Add(this.tarjetaLogin);
            this.AcceptButton = this.btnLogIn;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.ClientSize = new System.Drawing.Size(540, 650);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Name = "LogIn";
            this.Text = "Acceso";
            this.BackColor = System.Drawing.Color.FromArgb(245, 246, 249);
            this.ForeColor = System.Drawing.Color.FromArgb(35, 39, 45);
            this.Load += new System.EventHandler(this.LogIn_Load);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.LogIn_FormClosed);
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label subtituloLogin;
        private System.Windows.Forms.TextBox txtUser;
        private System.Windows.Forms.TextBox txtPassword;
        private ProyectoIS.UsuariosRoundedPanel tarjetaLogin;
        private ProyectoIS.UsuariosRoundedPanel campoUsuario;
        private ProyectoIS.UsuariosRoundedPanel campoClave;
        private ProyectoIS.UsuariosRoundedPanel insigniaLogin;
        private ProyectoIS.LoginGlyph iconoLogin;
        private ProyectoIS.LoginGlyph iconoUsuarioLogin;
        private ProyectoIS.LoginGlyph iconoClaveLogin;
        private ProyectoIS.UsuariosRoundedButton btnLogIn;
        private ProyectoIS.UsuariosRoundedButton btnCambiar;
        private ProyectoIS.UsuariosThemeSwitch temaLogin;
        private ProyectoIS.LoginEyeButton mostrarClave;
    }
}
